[tools]
awscli = "latest"
biome = "latest"
bun = "latest"
gh = "latest"
go = "latest"
lefthook = "latest"
node = "latest"
pnpm = "latest"
rust = "latest"
terraform = "latest"

[settings]
idiomatic_version_file_enable_tools = []
